image: eclipse-temurin:19-jdk

git-leaks:
  stage: .pre
  image:
    name: "zricethezav/gitleaks:latest"
    entrypoint: [""]
  script:
    - gitleaks detect --verbose --redact --no-git --source="$CI_PROJECT_DIR"
  tags:
    - docker

unit-test:
  stage: test
  script:
    - suffix=$([[ $(uname -m) == "aarch64" ]] && echo "arm64" || echo "x86-64")
    - curl -L -o agent https://app.testcontainers.cloud/download/testcontainers-cloud-agent_linux_$suffix
    - chmod +x agent
    - ./agent &
    - ./agent wait
    - chmod +x gradlew
    - ./gradlew jacocoTestReport
    - cat build/reports/jacoco/test/html/index.html
  tags:
    - docker

pages:
  stage: deploy
  image: beo1975/implementation-progress:1.4.0
  script:
    - cp -r /app/* ./
    - cp ci/application.yml BOOT-INF/classes/
    - dumb-init java org.springframework.boot.loader.JarLauncher
  artifacts:
    paths:
      - public
  rules:
    - if: ($NO_PAGES == null) && ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH)
  tags:
    - docker