image: eclipse-temurin:18-jdk

before_script:
  - chmod +x gradlew

unit_test:
  stage: test
  script:
    - curl -L -o agent https://app.testcontainers.cloud/download/testcontainers-cloud-agent_linux_x86-64
    - chmod +x agent
    - ./agent &
    - ./agent wait
    - ./gradlew jacocoTestReport
    - cat build/reports/jacoco/test/html/index.html
  tags:
    - docker

pages:
  stage: deploy
  script:
    - ./gradlew bootRun
  artifacts:
    paths:
      - public
  needs:
    - job: unit_test
  rules:
    - if: '$NO_PAGES == null'
  tags:
    - docker
